name: t3api
type: php
docroot: ~
no_project_mount: true
php_version: "7.4"
composer_version: 2
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
    - v10.t3api
    - v10-api.t3api
    - v11.t3api
    - v11-api.t3api
additional_fqdns: []
provider: default
use_dns_when_possible: true
extra_services:
    - v10-data
    - v11-data
hooks:
    pre-start:
        - exec-host: "mkdir -p .test/v10 .test/v11"
        - exec-host: "[ -L .test/t3api ] || ln -snvf ../. .test/t3api"
    post-start:
        - exec: sudo sed -i '1s/^/TERM=xterm-256color\n/' ~/.bashrc

